### ISSUE TITLE
Empty lines

### ISSUE THREAD

**Issue by molor** [McLive/SkinsRestorerX#88]
In v.13.3, `Locale.SR_LINE` is not sent in the chat if empty. After updated to version 13.4-SNAPSHOT, empty messages were sent to the chat. Is that right? What for?

https://github.com/McLive/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bukkit/commands/SrCommand.java#L31-L33

Can you return these checks? https://github.com/McLive/SkinsRestorerX/commit/2d172474823e0ad7ad5b67322390b7320f7dc790#diff-7efb853de037dd96c605e5931ef532f4

**Comment by McLive** [comment]
Yeah indeed I can do that.
